---
version: 1.0
name: 'Server failure'
description: 'Turn off a server'
tags:
  - prod
  - state
platform: aws
region: us-east-1
steady_states:
  - name: 'Check main site'
    type: 'http'
    endpoint: 'https://chaoscollector.ngrok.io/health'
    status: 200
steps:
  - name: 'Stop the server'
    action: 'stop_instances'
    parameters:
      instance_ids:
        -  "i-0eb96356f41ef95c1"
rollbacks:
  - name: 'Start the server'
    action: 'start_instances'
    parameters:
      instance_ids:
        -  "i-0eb96356f41ef95c1"